// CODE GENERATED BY YOUR-FRAMEWORK-PLUGIN. DO NOT EDIT.
package computev1

import "github.com/yourorg/archetype"

// Micro returns a generic Call configured with the "Micro" preset.
// Documentation: A cheap instance for dev environments.
func (c *ComputeServiceClient) Micro() *archetype.Call[*CreateInstanceRequest, *Instance] {
    // The generator parsed "{ 'cpu': 1... }" from the proto option 
    // and generated this struct initialization:
    seed := &CreateInstanceRequest{
        Cpu:   1,
        RamMb: 512,
        Image: "alpine",
    }
    return archetype.NewCall(seed, c.CreateInstance)
}

// HighPerformance returns a generic Call configured with the "HighPerformance" preset.
func (c *ComputeServiceClient) HighPerformance() *archetype.Call[*CreateInstanceRequest, *Instance] {
    seed := &CreateInstanceRequest{
        Cpu:   16,
        RamMb: 32000,
        Tags:  map[string]string{"class": "premium"},
    }
    return archetype.NewCall(seed, c.CreateInstance)
}

// WithGeographicLocation is generated because the 'zone' field was tagged.
// It matches the signature of the "Common Modifier" interface.
func WithGeographicLocation(val string) archetype.Modifier[*CreateInstanceRequest] {
    return func(r *CreateInstanceRequest) {
        r.Zone = val
    }
}
